import sys
from PyQt5 import QtCore, QtGui, QtWidgets, QtSql
from PyQt5.QtSql import*

class Ui_MainWindow(object):   
    def setupUi(self, MainWindow):
        self.genus = ""
        self.species = ""
        self.comName = ""
        self.db = None
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(789, 590)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.flowersLV = QtWidgets.QTableView(self.centralwidget)
        self.flowersLV.setGeometry(QtCore.QRect(10, 10, 381, 231))
        self.flowersLV.setObjectName("flowersLV")
        self.flowerSelect = QtWidgets.QPushButton(self.centralwidget)
        self.flowerSelect.setGeometry(QtCore.QRect(90, 490, 221, 51))
        self.flowerSelect.clicked.connect(self.selectFlower)
        font = QtGui.QFont()
        font.setFamily("Gentona")
        font.setPointSize(20)
        self.flowerSelect.setFont(font)
        self.flowerSelect.setObjectName("flowerSelect")
        self.recentTV = QtWidgets.QTableView(self.centralwidget)
        self.recentTV.setGeometry(QtCore.QRect(10, 250, 381, 231))
        self.recentTV.setObjectName("recentTV")
        self.genusLE = QtWidgets.QLineEdit(self.centralwidget)
        self.genusLE.setGeometry(QtCore.QRect(520, 50, 251, 20))
        self.genusLE.setObjectName("genusLE")
        self.updateLabel = QtWidgets.QLabel(self.centralwidget)
        self.updateLabel.setGeometry(QtCore.QRect(480, 10, 251, 31))
        font = QtGui.QFont()
        font.setFamily("QuadonW00-Regular")
        font.setPointSize(14)
        self.updateLabel.setFont(font)
        self.updateLabel.setObjectName("updateLabel")
        self.updateButton = QtWidgets.QPushButton(self.centralwidget)
        self.updateButton.setGeometry(QtCore.QRect(490, 160, 221, 51))
        self.updateButton.clicked.connect(self.updateFlower)
        font = QtGui.QFont()
        font.setFamily("Gentona")
        font.setPointSize(20)
        self.updateButton.setFont(font)
        self.updateButton.setObjectName("updateButton")
        self.genusLabel = QtWidgets.QLabel(self.centralwidget)
        self.genusLabel.setGeometry(QtCore.QRect(410, 51, 61, 20))
        font = QtGui.QFont()
        font.setFamily("QuadonW00-Regular")
        font.setPointSize(10)
        self.genusLabel.setFont(font)
        self.genusLabel.setObjectName("genusLabel")
        self.speciesLE = QtWidgets.QLineEdit(self.centralwidget)
        self.speciesLE.setGeometry(QtCore.QRect(520, 79, 251, 20))
        self.speciesLE.setObjectName("speciesLE")
        self.speciesLabel = QtWidgets.QLabel(self.centralwidget)
        self.speciesLabel.setGeometry(QtCore.QRect(410, 80, 61, 20))
        font = QtGui.QFont()
        font.setFamily("QuadonW00-Regular")
        font.setPointSize(10)
        self.speciesLabel.setFont(font)
        self.speciesLabel.setObjectName("speciesLabel")
        self.comnameLE = QtWidgets.QLineEdit(self.centralwidget)
        self.comnameLE.setGeometry(QtCore.QRect(520, 109, 251, 20))
        self.comnameLE.setObjectName("comnameLE")
        self.comnamLabel = QtWidgets.QLabel(self.centralwidget)
        self.comnamLabel.setGeometry(QtCore.QRect(410, 110, 101, 20))
        font = QtGui.QFont()
        font.setFamily("QuadonW00-Regular")
        font.setPointSize(10)
        self.comnamLabel.setFont(font)
        self.comnamLabel.setObjectName("comnamLabel")
        self.sightingLabel = QtWidgets.QLabel(self.centralwidget)
        self.sightingLabel.setGeometry(QtCore.QRect(480, 260, 261, 31))
        font = QtGui.QFont()
        font.setFamily("QuadonW00-Regular")
        font.setPointSize(14)
        self.sightingLabel.setFont(font)
        self.sightingLabel.setObjectName("sightingLabel")
        self.flownameLE = QtWidgets.QLineEdit(self.centralwidget)
        self.flownameLE.setGeometry(QtCore.QRect(520, 300, 251, 20))
        self.flownameLE.setObjectName("flownameLE")
        self.locationLE = QtWidgets.QLineEdit(self.centralwidget)
        self.locationLE.setGeometry(QtCore.QRect(520, 359, 251, 20))
        self.locationLE.setObjectName("locationLE")
        self.personLabel = QtWidgets.QLabel(self.centralwidget)
        self.personLabel.setGeometry(QtCore.QRect(410, 330, 61, 20))
        font = QtGui.QFont()
        font.setFamily("QuadonW00-Regular")
        font.setPointSize(10)
        self.personLabel.setFont(font)
        self.personLabel.setObjectName("personLabel")
        self.personLE = QtWidgets.QLineEdit(self.centralwidget)
        self.personLE.setGeometry(QtCore.QRect(520, 329, 251, 20))
        self.personLE.setObjectName("personLE")
        self.insertButton = QtWidgets.QPushButton(self.centralwidget)
        self.insertButton.setGeometry(QtCore.QRect(490, 440, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Gentona")
        font.setPointSize(20)
        self.insertButton.setFont(font)
        self.insertButton.setObjectName("insertButton")
        self.insertButton.clicked.connect(self.insertSighting)
        self.locationLabel = QtWidgets.QLabel(self.centralwidget)
        self.locationLabel.setGeometry(QtCore.QRect(410, 360, 101, 20))
        font = QtGui.QFont()
        font.setFamily("QuadonW00-Regular")
        font.setPointSize(10)
        self.locationLabel.setFont(font)
        self.locationLabel.setObjectName("locationLabel")
        self.flownameLabel = QtWidgets.QLabel(self.centralwidget)
        self.flownameLabel.setGeometry(QtCore.QRect(410, 301, 91, 20))
        font = QtGui.QFont()
        font.setFamily("QuadonW00-Regular")
        font.setPointSize(10)
        self.flownameLabel.setFont(font)
        self.flownameLabel.setObjectName("flownameLabel")
        self.dateLE = QtWidgets.QLineEdit(self.centralwidget)
        self.dateLE.setGeometry(QtCore.QRect(520, 389, 251, 20))
        self.dateLE.setObjectName("dateLE")
        self.dateLabel = QtWidgets.QLabel(self.centralwidget)
        self.dateLabel.setGeometry(QtCore.QRect(410, 390, 101, 20))
        font = QtGui.QFont()
        font.setFamily("QuadonW00-Regular")
        font.setPointSize(10)
        self.dateLabel.setFont(font)
        self.dateLabel.setObjectName("dateLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 789, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.flowerSelect.setText(_translate("MainWindow", "Select Flower"))
        self.updateLabel.setText(_translate("MainWindow", "Update Flower Information"))
        self.updateButton.setText(_translate("MainWindow", "Update"))
        self.genusLabel.setText(_translate("MainWindow", "Genus"))
        self.speciesLabel.setText(_translate("MainWindow", "Species"))
        self.comnamLabel.setText(_translate("MainWindow", "Common Name"))
        self.sightingLabel.setText(_translate("MainWindow", "Insert Sighting Information"))
        self.personLabel.setText(_translate("MainWindow", "Person"))
        self.insertButton.setText(_translate("MainWindow", "Insert"))
        self.locationLabel.setText(_translate("MainWindow", "Location"))
        self.flownameLabel.setText(_translate("MainWindow", "Flower Name"))
        self.dateLabel.setText(_translate("MainWindow", "Date Sighted"))

    def initializeModel(self):
        model = QSqlTableModel()
        model.setTable("FLOWERS")
        model.select()
        self.flowersLV.setModel(model)
        header = self.flowersLV.horizontalHeader()       
        header.setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(1, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(2, QtWidgets.QHeaderView.ResizeToContents)
        self.flowersLV.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.flowersLV.setSelectionBehavior(QtWidgets.QTableView.SelectRows)
        self.flowersLV.show()

    def updateFlower(self):
        query = """UPDATE FLOWERS SET genus = '%s', species = '%s', comname = '%s' WHERE genus = '%s' AND species = '%s' AND comname = '%s'""" % (self.genusLE.text(), self.speciesLE.text(), self.comnameLE.text(), self.genus, self.species, self.comName)
        q = QtSql.QSqlQuery()
        q.exec_(query)
        self.genusLE.setText(None)
        self.speciesLE.setText(None)
        self.comnameLE.setText(None)
        self.initializeModel()

    def displaySightings(self, comName):
        model = QSqlQueryModel()
        query = """SELECT person, location, sighted FROM SIGHTINGS WHERE name = '%s' ORDER BY sighted DESC LIMIT 10""" % (comName)
        model.setQuery(query)
        self.recentTV.setModel(model)
        header = self.recentTV.horizontalHeader()       
        header.setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(1, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(2, QtWidgets.QHeaderView.ResizeToContents)
        self.recentTV.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.recentTV.setSelectionBehavior(QtWidgets.QTableView.SelectRows)
        self.recentTV.show()
        
    def selectFlower(self):
        if(len(self.flowersLV.selectedIndexes()) == 3):
            self.genus = self.flowersLV.selectedIndexes()[0].data()
            self.species = self.flowersLV.selectedIndexes()[1].data()
            self.comName = self.flowersLV.selectedIndexes()[2].data()
            self.genusLE.setText(self.genus)
            self.speciesLE.setText(self.species)
            self.comnameLE.setText(self.comName)
            self.displaySightings(self.comName)

    def insertSighting(self):
        query = """INSERT INTO SIGHTINGS(name, person, location, sighted) VALUES ('%s', '%s', '%s', '%s')""" % (self.flownameLE.text(), self.personLE.text(), self.locationLE.text(), self.dateLE.text())
        q = QtSql.QSqlQuery()
        q.exec_(query)
        self.flownameLE.setText(None)
        self.personLE.setText(None)
        self.locationLE.setText(None)
        self.dateLE.setText(None)
        
def main():
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    
    db = QtSql.QSqlDatabase.addDatabase('QSQLITE')
    db.setDatabaseName('flowers2019.db')
    ui.db = db
    
    ui.initializeModel()

    sys.exit(app.exec_())

if __name__ == "__main__":
    main()
